name: build 1st workshop

on: push

jobs: 
  greetings:
    runs-on: ubuntu-latest
    steps: 
    - name: Hello World
      run: exho "hello World"
    - name: echo server.js
      run: node server.js