name: build 1st workshop

on: push

jobs: 
  greetings:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - name: Hello World
      run: echo "hello World"
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: echo server.js
      run: node server.js